# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: bookalbum
#   name: bookalbum
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#   selector:
#     app: bookalbum

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
spec:
  type: NodePort
  ports:
    - port: 80  # Expose port 80 externally
      targetPort: 3000  # Assuming your Node.js app listens on port 3000 internally
      protocol: TCP
  selector:
    app: nodejs-app
