apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      # hostname: "231058010_Tejas_M"
      containers:
      - name: nodejs-app
        image: tejasmohan8/nodejsdocker:v1  # Update the image name to tejasmohan8/nodejsdocker:v1
        ports:
        - containerPort: 3000  # Assuming your Node.js app listens on port 3000
